name: Deploy Backup to GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Docker image
        run: |
          docker build \
            --build-arg CI_TOKEN=${{ secrets.CI_TOKEN }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -t dbmigrations .

      - name: Run Docker container
        run: |
          docker run \
            -e CI_TOKEN=${{ secrets.CI_TOKEN }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            dbmigrations
