name: Run Dbmate Migrations

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbmate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional, for advanced multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t dbmate-npm-container .

      # Step 5: Run Dbmate migrations using the Docker image, passing the DATABASE_URL from GitHub Secrets
      - name: Run Dbmate migrations
        run: docker run --rm -e DATABASE_URL="${{ secrets.DATABASE_URL }}" dbmate-npm-container
